In [1]:
# array has way more methods as compared to list, also when u create a sliece of an array u r not creating a new copie
# of array it just create a view of array

In [1]:
a=[1,2,3,4,5,6,7,8,9]

In [5]:
b= a[3:6]

In [6]:
b

[4, 5, 6]

In [7]:
b[2]=10

In [8]:
b

[4, 5, 10]

In [9]:
a

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [25]:
# When we replaced 6 with 10 in list "b", the value 6 in list "a" remained as it is. In Array this is not the case. 

In [2]:
import numpy as np

In [3]:
c=np.array(a)

In [4]:
d=c[3:6]

In [5]:
d

array([4, 5, 6])

In [6]:
d[2]=10

In [7]:
d

array([ 4,  5, 10])

In [8]:
c

array([ 1,  2,  3,  4,  5, 10,  7,  8,  9])

In [48]:
# Here 6 in the primary array "c" also got replaced when 6 in the array "d" is changed

---

In [1]:
# To make a copy of array u can use

In [17]:
e=c.copy()

In [18]:
e

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
f=e[2:5]

In [22]:
f

array([3, 4, 5])

In [23]:
f[:]= 11

In [24]:
f

array([11, 11, 11])

In [25]:
e

array([ 1,  2, 11, 11, 11,  6,  7,  8,  9])

In [26]:
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
# "c" array has elements as it was because copy fun creates a new copy of array thus primary array dose'nt get changed 
# if changes made to copy array